### PR TITLE
Update to use the official truffle ganache-cli

### PR DESCRIPTION
**Pull request by mbeacom**
The goal of this PR is to replace the custom Dockerfile with the official testrpc/ganace-cli image provided via docker hub.

### CODE REVIEW

**Comment by owocki** [comment]
i don't mind using either or.  

1. is their an easy way to get to the ganache UI within the docker container?
2. should we maybe give users the option of doing either ganache OR testrpc?  maybe this repo could support both..

**Comment by mbeacom** [comment]
@owocki
1. I can update the existing provisioning scripts to install/launch `ganache-cli` over `testrpc` if they wanted to run it locally versus docker container.  Would you like me to do that?
2. `testrpc` node package was deprecated in favor of `ganache-cli` - I can switch it back to use `testrpc` but it's no longer being updated, since `ganache-cli` is the direct replacement from the same publisher.

**Comment by owocki** [comment]
> testrpc node package was deprecated in favor of ganache-cli

ahhh.. neato.   i did not know that

**Comment by owocki** [comment]
im thinking im gonna merge this.  anyone have objections?

**Pull request merged**
