### PR TITLE
Add package.json

### PR DESCRIPTION
**Pull request by sc0Vu**
Test node version: 8.9.1
Test npm version: 5.5.1

What I've done:

* Add package.json file.
* Ignore package-lock.json file.
* Edit README.md.
  
Issues: #17 #18

### CODE REVIEW

**Comment by owocki** [comment]
this looks good to me... but im not great with npm stuff. @mbeacom @step21 what do you think?

**Comment by step21** [comment]
Looks like a good start, but wouldn't it also need truffle the package?
Apart from that I couldn't test it properly because it cannot get tries to get git://github.com/frozeman/WebSocket-Node.git as a dependency and fails, probably because of github permission and https not being set (as in (git+https) )

**Comment by nlaz** [comment]
It is a [good practice to lock down dependencies](https://blog.risingstack.com/nodejs-at-scale-npm-best-practices/) so multiple applications running `npm install` will have the same results. This means either including a dependency lock file, i.e.`package-lock.json`, or `yarn.lock`(preferable) or having specific version numbers in the manifest (package.json).

**Comment by step21** [comment]
@nlaz I know what the package-lock.json file is there. But tbh I would prefer proper version numbers in packages.json as package-lock will capture everything that person x might have installed in the directory for testing or whatever and yarn introduced another thing to install.

**Comment by step21** [comment]
For the git issue, there was a workaround described here https://github.com/npm/npm/issues/5257#issuecomment-60441477 but that is not feasible for me as I cannot set a global replace for git with https as then my other repos would probably fail. Why do people in dependencies write git urls in the first place :-1:

**Comment by nlaz** [comment]
>  as package-lock will capture everything that person x might have installed in the directory for testing or whatever

That seems fine to me. If the packages installed need to be included they should be checked in. If not, they should not be checked in. Having different dependency versions isn't encouraged because _it might_ lead to weird bugs and this also applies to the dependency tree which `package-lock` locks down but `package.json` does not. Not a blocker though, just thought I would add my two cents.

**Comment by step21** [comment]
Yeah, I was specifically referring to the fact that it includes stuff that it is not 'checked-in' unless you manually fix your package-lock.json.

**Comment by owocki** [comment]
whats the verdict folks? 👌 to merge? :)

**Comment by sc0Vu** [comment]
I think it good to add truffle package and package-lock.json:) 
Do it now.

**Comment by nlaz** [comment]
LGTM 👌

**Comment by owocki** [comment]
tyty

**Pull request merged**
